### ISSUE TITLE
Missing ª character

### ISSUE THREAD

**Issue by dafzor** [g7fernandes/us-international-pt-improved-keyboard-xkb#1]
Been trying out this layout for two days and noticed there's no way to write ª.

I took a look at the configuration for windows and it doesn't seem present, while it's not frequent character to write it seemed an odd omission to this layout given it's prominence in the Portuguese layout.

Adding it on `alt gr + h` or other unused space seems it would have minimal impact.

**Comment by g7fernandes** [comment]
@dafzor Thanks for the report. I was using the  [compose key](https://www.x.org/releases/X11R7.7/doc/libX11/i18n/compose/en_US.UTF-8.html) for creating ª and º. I will update it.

**Comment by dafzor** [comment]
Wasn't familiar with that feature but seems to be linux only? So by updating do you mean adding a new bind on the layout or adding instructions for using compose keys?

**Comment by g7fernandes** [comment]
I will upgrade the layout to put  ª and º on vacant spaces. According to [wikipedia](https://en.wikipedia.org/wiki/Compose_key#Windows), compose key requires extra software on Windows. On linux with gnome, one can [just activate on the Gnome Tweaks](https://help.ubuntu.com/community/ComposeKey).

**Comment by g7fernandes** [comment]
I'm working on [this branch]https://github.com/g7fernandes/us-international-pt-improved-keyboard-xkb/pull/2). When I get access to my Windows I will edit the MS Layouts.
